__title__ = "smart_path"
__version__ = "1.0.1"
__author__ = "Zhaoyi Wan"
__author_email__ = "i@wanzy.me"
__url__ = "https://github.com/wanzysky/smart_path"
__description__ = "Smart dispatch between pathlib.Path and s3path.S3Path. It was borrowed from the project by EMTF: emtf@megvii.com"
